#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
mortality.f90 \
veg_dyn.f90 \
vegetation_dyn.f90 \
output_vegdyn.f90 \
growth.f90 \
dispersal.f90 

SRCS_dspd2 = \
writexml.dsp \
tst_process.dsp \
tst_grid.dsp \
tst_array_of_words.dsp \
tst_menu.dsp \
assem_t.dsp \
array_of_words.dsp \
tst_readint.dsp 

SRCS_f90d3 = \
Set_rain_xml.f90 \
calibration_xml.f90 \
Set_rain_new_xml.f90 \
output_file_definition_xml.f90 \
output_markers_xml.f90 \
calculate_surface_properties_from_types.f90 \
marked_cell_xml.f90 \
initialize_markers _xml.f90 \
initialize_values_xml.f90 \
read_spatial_data.f90 \
initialize_allocatables.f90 \
echo_params_xml.f90 \
read_markers_xml.f90 \
output_hydro_data_xml.f90 \
output_maps_xml.f90 \
find_output_file_xml.f90 \
output_markers_xy_xml.f90 \
read_parameters_from_xml_file.f90 

SRCS_ford3 = \
read_sm_map.for \
Set_rain.for \
dynamic_topog_attrib.for \
output_markers.for \
output_hydro_data.for \
output_markers_xy.for \
contrib_area.for \
read_rain_map.for \
output_file_definition.for \
dynamic_topog_attribute.for \
read_cover_map.for \
output_maps.for \
read_topog.for \
read_parameters.for \
Functions.for \
Set_rain_new.for \
topog_attrib.for \
read_veg_map.for \
topog_attribute.for \
read_pavement_map.for \
read_markers.for \
initialize_values_xml.for \
initialize_allocatables.for \
read_parameters1_01_6.for \
marked_cell.for \
read_rain_mask.for \
read_theta_sat_map.for \
read_ff_map.for \
calibration.for \
read_ksat_map.for \
aspect_z_4.for \
read_Phi_maps.for \
echo_params.for \
initialise_markers.for \
topog_attributes.for \
find_output_file.for 

SRCS_ford4 = \
route_water.for \
update_water_flow.for \
route_water - Copy.for \
accumulate_flow.for \
downslope_vars.for \
infilt.for 

SRCS_incd5 = \
read_xml_array.inc \
read_xml_scalar.inc \
read_from_buffer.inc 

SRCS_for_oldd3 = \
echo_params.for_old \
Set_rain.for_old \
output_hydro_data.for_old \
contrib_area.for_old \
calibration.for_old 

SRCS_xmld2 = \
simple.xml \
readint.xml \
array_of_words.xml \
menu.xml \
output_words.xml \
example.xml \
assem_t.xml \
out_grid.xml \
grid_example.xml \
readint_example.xml \
example_words.xml \
menuitems.xml \
grid.xml 

SRCS_f90d6 = \
calc_sm.f90 \
interstorm_initialise.f90 \
read_interstorm_parameters.f90 \
Annual_statistics.f90 \
read_temperature_daily.f90 \
interstorm_initialize_xml.f90 \
read_shrub_cov.f90 \
general_h.f90 \
output_maps_within_storm_xml.f90 \
calcday.f90 \
theta_areal_average.f90 \
output_interstorm_fluxes.f90 \
read_rainfall_minute_xml.f90 \
calc_et.f90 \
read_rainfall_minute.f90 \
output_interstorm.f90 \
read_rainfall_daily.f90 \
calc_inf.f90 \
output_interstorm_xml.f90 \
read_rainfall_daily_xml.f90 \
calcyear.f90 \
read_interstorm_parameters_xml.f90 \
read_temperature_daily_xml.f90 \
read_shrub_cov_xml.f90 

SRCS_f90d5 = \
test_read_prims.f90 \
test_write_prims.f90 \
tst_prims.f90 \
write_xml_prims.f90 \
xmlreader.f90 \
xmlreader_noprint.f90 \
tree_find.f90 \
tstparse.f90 \
read_xml_prims.f90 \
xsdconvert.f90 \
xmlparse.f90 \
tree_struct.f90 

SRCS_dswd5 = \
tstparse.dsw \
test_write_prims.dsw \
xmlreader.dsw 

SRCS_confd5 = \
xmlreader.conf 

SRCS_for~d3 = \
read_parameters.for~ \
output_hydro_data.for~ \
echo_params.for~ \
read_cover_map.for~ \
read_theta_sat_map.for~ \
calibration.for~ \
initialize_values.for~ 

SRCS_f90d7 = \
diffuse_transport_markers_xml.f90 \
route_sediment_xml.f90 \
route_markers_xml.f90 \
trans_detach_markers_xml.f90 \
suspended_markers_xml.f90 \
bedload_markers_xml.f90 \
splash_transport_markers_xml.f90 \
splash_detach_markers_xml.f90 \
susp_trajectories_xml.f90 

SRCS_ford7 = \
splash_transport_markers.for \
flow_distrib.for \
diffuse_transport_markers.for \
splash_detach_markers.for \
conc_flow_transport.for \
susp_trajectories.for \
suspended_markers.for \
flow_detachment.for \
splash_transport.for \
raindrop_detachment.for \
update_top_surface.for \
update_sediment_flow.for \
route_sediment.for \
route_markers.for \
diffuse_flow_transport.for \
trans_detach_markers.for \
suspended_transport.for \
bedload_markers.for 

SRCS_dswd2 = \
writexml.dsw \
tst_grid.dsw \
tst_readint.dsw \
tst_array_of_words.dsw \
tst_process.dsw \
tst_menu.dsw 

SRCS_htmld8 = \
xmlparse.html 

SRCS_d2 = \
makefile 

SRCS_f90d9 = \
MAHLERAN_interstorm_setting_xml.f90 \
interstorm_shared_data.f90 \
MAHLERAN_vegdyn_setting.f90 \
mt95.f90 \
vegdynamics_shared_data.f90 \
parameters_from_xml.f90 \
MAHLERAN_1_2_2.f90 \
MAHLERAN_interstorm_xml.f90 \
MAHLERAN_vegdyn_setting_xml.f90 \
shared_data.f90 \
theta_areal_average.f90 

SRCS_inpd5 = \
xmlreader.inp \
tstparse.inp 

SRCS_for~d7 = \
route_sediment.for~ 

SRCS_vard3 = \
allocat.var \
allocat_markers.var 

SRCS_vard6 = \
allocat_general.var 

SRCS_ford10 = \
update_chemistry_flow.for \
route_chemistry.for 

SRCS_d11 = \
TODO \
CHANGES \
README 

SRCS_d5 = \
makefile 

SRCS_dspd5 = \
xmlreader.dsp \
tstparse.dsp \
test_write_prims.dsp 

SRCS_pdfd8 = \
gettingstarted.pdf \
using_xml_files.pdf \
xml_again.pdf 

SRCS_for_oldd4 = \
route_water.for_old 

SRCS_for~d10 = \
route_chemistry.for~ 

SRCS_var_oldd3 = \
allocat.var_old 

SRCS_for_oldd7 = \
route_sediment.for_old 

OBJS_f90d1 = \
mortality.o \
veg_dyn.o \
vegetation_dyn.o \
output_vegdyn.o \
growth.o \
dispersal.o 

OBJS_dspd2 = \


OBJS_f90d3 = \
Set_rain_xml.o \
calibration_xml.o \
Set_rain_new_xml.o \
output_file_definition_xml.o \
output_markers_xml.o \
calculate_surface_properties_from_types.o \
marked_cell_xml.o \
initialize_markers _xml.o \
initialize_values_xml.o \
read_spatial_data.o \
initialize_allocatables.o \
echo_params_xml.o \
read_markers_xml.o \
output_hydro_data_xml.o \
output_maps_xml.o \
find_output_file_xml.o \
output_markers_xy_xml.o \
read_parameters_from_xml_file.o 

OBJS_ford3 = \
read_sm_map.o \
Set_rain.o \
dynamic_topog_attrib.o \
output_markers.o \
output_hydro_data.o \
output_markers_xy.o \
contrib_area.o \
read_rain_map.o \
output_file_definition.o \
dynamic_topog_attribute.o \
read_cover_map.o \
output_maps.o \
read_topog.o \
read_parameters.o \
Functions.o \
Set_rain_new.o \
topog_attrib.o \
read_veg_map.o \
topog_attribute.o \
read_pavement_map.o \
read_markers.o \
initialize_values_xml.o \
initialize_allocatables.o \
read_parameters1_01_6.o \
marked_cell.o \
read_rain_mask.o \
read_theta_sat_map.o \
read_ff_map.o \
calibration.o \
read_ksat_map.o \
aspect_z_4.o \
read_Phi_maps.o \
echo_params.o \
initialise_markers.o \
topog_attributes.o \
find_output_file.o 

OBJS_ford4 = \
route_water.o \
update_water_flow.o \
route_water - Copy.o \
accumulate_flow.o \
downslope_vars.o \
infilt.o 

OBJS_incd5 = \


OBJS_for_oldd3 = \


OBJS_xmld2 = \


OBJS_f90d6 = \
calc_sm.o \
interstorm_initialise.o \
read_interstorm_parameters.o \
Annual_statistics.o \
read_temperature_daily.o \
interstorm_initialize_xml.o \
read_shrub_cov.o \
general_h.o \
output_maps_within_storm_xml.o \
calcday.o \
theta_areal_average.o \
output_interstorm_fluxes.o \
read_rainfall_minute_xml.o \
calc_et.o \
read_rainfall_minute.o \
output_interstorm.o \
read_rainfall_daily.o \
calc_inf.o \
output_interstorm_xml.o \
read_rainfall_daily_xml.o \
calcyear.o \
read_interstorm_parameters_xml.o \
read_temperature_daily_xml.o \
read_shrub_cov_xml.o 

OBJS_f90d5 = \
test_read_prims.o \
test_write_prims.o \
tst_prims.o \
write_xml_prims.o \
xmlreader.o \
xmlreader_noprint.o \
tree_find.o \
tstparse.o \
read_xml_prims.o \
xsdconvert.o \
xmlparse.o \
tree_struct.o 

OBJS_dswd5 = \


OBJS_confd5 = \


OBJS_for~d3 = \


OBJS_f90d7 = \
diffuse_transport_markers_xml.o \
route_sediment_xml.o \
route_markers_xml.o \
trans_detach_markers_xml.o \
suspended_markers_xml.o \
bedload_markers_xml.o \
splash_transport_markers_xml.o \
splash_detach_markers_xml.o \
susp_trajectories_xml.o 

OBJS_ford7 = \
splash_transport_markers.o \
flow_distrib.o \
diffuse_transport_markers.o \
splash_detach_markers.o \
conc_flow_transport.o \
susp_trajectories.o \
suspended_markers.o \
flow_detachment.o \
splash_transport.o \
raindrop_detachment.o \
update_top_surface.o \
update_sediment_flow.o \
route_sediment.o \
route_markers.o \
diffuse_flow_transport.o \
trans_detach_markers.o \
suspended_transport.o \
bedload_markers.o 

OBJS_dswd2 = \


OBJS_htmld8 = \


OBJS_d2 = \


OBJS_f90d9 = \
MAHLERAN_interstorm_setting_xml.o \
interstorm_shared_data.o \
MAHLERAN_vegdyn_setting.o \
mt95.o \
vegdynamics_shared_data.o \
parameters_from_xml.o \
MAHLERAN_1_2_2.o \
MAHLERAN_interstorm_xml.o \
MAHLERAN_vegdyn_setting_xml.o \
shared_data.o \
theta_areal_average.o 

OBJS_inpd5 = \


OBJS_for~d7 = \


OBJS_vard3 = \


OBJS_vard6 = \


OBJS_ford10 = \
update_chemistry_flow.o \
route_chemistry.o 

OBJS_d11 = \


OBJS_d5 = \


OBJS_dspd5 = \


OBJS_pdfd8 = \


OBJS_for_oldd4 = \


OBJS_for~d10 = \


OBJS_var_oldd3 = \


OBJS_for_oldd7 = \


SRC_DIR_f90d1 = Mahleran_v1.2.2_source files/Subroutines_Vegetation/

SRC_DIR_dspd2 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/examples/

SRC_DIR_f90d3 = Mahleran_v1.2.2_source files/Subroutines_in_out/

SRC_DIR_ford3 = Mahleran_v1.2.2_source files/Subroutines_in_out/

SRC_DIR_ford4 = Mahleran_v1.2.2_source files/Subroutines_Water/

SRC_DIR_incd5 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/src/

SRC_DIR_for_oldd3 = Mahleran_v1.2.2_source files/Subroutines_in_out/

SRC_DIR_xmld2 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/examples/

SRC_DIR_f90d6 = Mahleran_v1.2.2_source files/Subroutine_Interstorm/

SRC_DIR_f90d5 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/src/

SRC_DIR_dswd5 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/src/

SRC_DIR_confd5 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/src/

SRC_DIR_for~d3 = Mahleran_v1.2.2_source files/Subroutines_in_out/

SRC_DIR_f90d7 = Mahleran_v1.2.2_source files/Subroutines_Sediment/

SRC_DIR_ford7 = Mahleran_v1.2.2_source files/Subroutines_Sediment/

SRC_DIR_dswd2 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/examples/

SRC_DIR_htmld8 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/doc/

SRC_DIR_d2 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/examples/

SRC_DIR_f90d9 = Mahleran_v1.2.2_source files/

SRC_DIR_inpd5 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/src/

SRC_DIR_for~d7 = Mahleran_v1.2.2_source files/Subroutines_Sediment/

SRC_DIR_vard3 = Mahleran_v1.2.2_source files/Subroutines_in_out/

SRC_DIR_vard6 = Mahleran_v1.2.2_source files/Subroutine_Interstorm/

SRC_DIR_ford10 = Mahleran_v1.2.2_source files/Subroutines_Chemistry/

SRC_DIR_d11 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/

SRC_DIR_d5 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/src/

SRC_DIR_dspd5 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/src/

SRC_DIR_pdfd8 = Mahleran_v1.2.2_source files/Subroutines_in_out/xml-fortran/doc/

SRC_DIR_for_oldd4 = Mahleran_v1.2.2_source files/Subroutines_Water/

SRC_DIR_for~d10 = Mahleran_v1.2.2_source files/Subroutines_Chemistry/

SRC_DIR_var_oldd3 = Mahleran_v1.2.2_source files/Subroutines_in_out/

SRC_DIR_for_oldd7 = Mahleran_v1.2.2_source files/Subroutines_Sediment/
OBJS_DIR = obj/Debug/Mahleran_v1.2.2_source files/Subroutines_Vegetation/
EXE_DIR = bin/Debug/

EXE = MAHLERAN_v1.2.2.exe
FC = gfortran.exe
LD = gfortran.exe
IDIR = 
CFLAGS = -Wall -g  -J$(OBJS_DIR) $(IDIR)
LFLAGS = 
LIBS = 

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR):$(SRC_DIR_dspd2):$(OBJS_DIR):$(SRC_DIR_f90d3):$(OBJS_DIR):$(SRC_DIR_ford3):$(OBJS_DIR):$(SRC_DIR_ford4):$(OBJS_DIR):$(SRC_DIR_incd5):$(OBJS_DIR):$(SRC_DIR_for_oldd3):$(OBJS_DIR):$(SRC_DIR_xmld2):$(OBJS_DIR):$(SRC_DIR_f90d6):$(OBJS_DIR):$(SRC_DIR_f90d5):$(OBJS_DIR):$(SRC_DIR_dswd5):$(OBJS_DIR):$(SRC_DIR_confd5):$(OBJS_DIR):$(SRC_DIR_for~d3):$(OBJS_DIR):$(SRC_DIR_f90d7):$(OBJS_DIR):$(SRC_DIR_ford7):$(OBJS_DIR):$(SRC_DIR_dswd2):$(OBJS_DIR):$(SRC_DIR_htmld8):$(OBJS_DIR):$(SRC_DIR_d2):$(OBJS_DIR):$(SRC_DIR_f90d9):$(OBJS_DIR):$(SRC_DIR_inpd5):$(OBJS_DIR):$(SRC_DIR_for~d7):$(OBJS_DIR):$(SRC_DIR_vard3):$(OBJS_DIR):$(SRC_DIR_vard6):$(OBJS_DIR):$(SRC_DIR_ford10):$(OBJS_DIR):$(SRC_DIR_d11):$(OBJS_DIR):$(SRC_DIR_d5):$(OBJS_DIR):$(SRC_DIR_dspd5):$(OBJS_DIR):$(SRC_DIR_pdfd8):$(OBJS_DIR):$(SRC_DIR_for_oldd4):$(OBJS_DIR):$(SRC_DIR_for~d10):$(OBJS_DIR):$(SRC_DIR_var_oldd3):$(OBJS_DIR):$(SRC_DIR_for_oldd7):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1) $(OBJS_dspd2) $(OBJS_f90d3) $(OBJS_ford3) $(OBJS_ford4) $(OBJS_incd5) $(OBJS_for_oldd3) $(OBJS_xmld2) $(OBJS_f90d6) $(OBJS_f90d5) $(OBJS_dswd5) $(OBJS_confd5) $(OBJS_for~d3) $(OBJS_f90d7) $(OBJS_ford7) $(OBJS_dswd2) $(OBJS_htmld8) $(OBJS_d2) $(OBJS_f90d9) $(OBJS_inpd5) $(OBJS_for~d7) $(OBJS_vard3) $(OBJS_vard6) $(OBJS_ford10) $(OBJS_d11) $(OBJS_d5) $(OBJS_dspd5) $(OBJS_pdfd8) $(OBJS_for_oldd4) $(OBJS_for~d10) $(OBJS_var_oldd3) $(OBJS_for_oldd7))

all : $(EXE)

$(EXE) : $(OBJS_f90d1) $(OBJS_dspd2) $(OBJS_f90d3) $(OBJS_ford3) $(OBJS_ford4) $(OBJS_incd5) $(OBJS_for_oldd3) $(OBJS_xmld2) $(OBJS_f90d6) $(OBJS_f90d5) $(OBJS_dswd5) $(OBJS_confd5) $(OBJS_for~d3) $(OBJS_f90d7) $(OBJS_ford7) $(OBJS_dswd2) $(OBJS_htmld8) $(OBJS_d2) $(OBJS_f90d9) $(OBJS_inpd5) $(OBJS_for~d7) $(OBJS_vard3) $(OBJS_vard6) $(OBJS_ford10) $(OBJS_d11) $(OBJS_d5) $(OBJS_dspd5) $(OBJS_pdfd8) $(OBJS_for_oldd4) $(OBJS_for~d10) $(OBJS_var_oldd3) $(OBJS_for_oldd7)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_dspd2):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_dspd2)$(@:.o=.dsp) -o $(OBJS_DIR)$@

$(OBJS_f90d3):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d3)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_ford3):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_ford3)$(@:.o=.for) -o $(OBJS_DIR)$@

$(OBJS_ford4):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_ford4)$(@:.o=.for) -o $(OBJS_DIR)$@

$(OBJS_incd5):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_incd5)$(@:.o=.inc) -o $(OBJS_DIR)$@

$(OBJS_for_oldd3):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_for_oldd3)$(@:.o=.for_old) -o $(OBJS_DIR)$@

$(OBJS_xmld2):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_xmld2)$(@:.o=.xml) -o $(OBJS_DIR)$@

$(OBJS_f90d6):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d6)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_f90d5):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d5)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_dswd5):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_dswd5)$(@:.o=.dsw) -o $(OBJS_DIR)$@

$(OBJS_confd5):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_confd5)$(@:.o=.conf) -o $(OBJS_DIR)$@

$(OBJS_for~d3):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_for~d3)$(@:.o=.for~) -o $(OBJS_DIR)$@

$(OBJS_f90d7):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d7)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_ford7):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_ford7)$(@:.o=.for) -o $(OBJS_DIR)$@

$(OBJS_dswd2):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_dswd2)$(@:.o=.dsw) -o $(OBJS_DIR)$@

$(OBJS_htmld8):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_htmld8)$(@:.o=.html) -o $(OBJS_DIR)$@

$(OBJS_d2):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_d2)$(@:.o=.) -o $(OBJS_DIR)$@

$(OBJS_f90d9):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d9)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_inpd5):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_inpd5)$(@:.o=.inp) -o $(OBJS_DIR)$@

$(OBJS_for~d7):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_for~d7)$(@:.o=.for~) -o $(OBJS_DIR)$@

$(OBJS_vard3):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_vard3)$(@:.o=.var) -o $(OBJS_DIR)$@

$(OBJS_vard6):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_vard6)$(@:.o=.var) -o $(OBJS_DIR)$@

$(OBJS_ford10):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_ford10)$(@:.o=.for) -o $(OBJS_DIR)$@

$(OBJS_d11):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_d11)$(@:.o=.) -o $(OBJS_DIR)$@

$(OBJS_d5):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_d5)$(@:.o=.) -o $(OBJS_DIR)$@

$(OBJS_dspd5):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_dspd5)$(@:.o=.dsp) -o $(OBJS_DIR)$@

$(OBJS_pdfd8):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_pdfd8)$(@:.o=.pdf) -o $(OBJS_DIR)$@

$(OBJS_for_oldd4):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_for_oldd4)$(@:.o=.for_old) -o $(OBJS_DIR)$@

$(OBJS_for~d10):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_for~d10)$(@:.o=.for~) -o $(OBJS_DIR)$@

$(OBJS_var_oldd3):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_var_oldd3)$(@:.o=.var_old) -o $(OBJS_DIR)$@

$(OBJS_for_oldd7):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_for_oldd7)$(@:.o=.for_old) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files

